// <auto-generated />
using System;
using ExpensesTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesTracker.Models.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250201074139_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesTracker.Models.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6a1f847-0f02-4a4b-a60d-d6235b2e2c6a"),
                            Amount = 31m,
                            Category = 20,
                            CreateDt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Details5",
                            Name = "Item1"
                        },
                        new
                        {
                            Id = new Guid("be9a88f1-2e01-4bc5-8e3f-5e1c7a02b4b1"),
                            Amount = 123m,
                            Category = 10,
                            CreateDt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Details1",
                            Name = "Item2"
                        },
                        new
                        {
                            Id = new Guid("93ab05e5-fc5b-4cc3-b04e-93cb5d7c2f41"),
                            Amount = 2345m,
                            Category = 20,
                            CreateDt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Details2",
                            Name = "Item3"
                        },
                        new
                        {
                            Id = new Guid("fcab3cbb-8e02-4b79-b1f8-11dbf4c0910a"),
                            Amount = 591m,
                            Category = 10,
                            CreateDt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2023, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Details3",
                            Name = "Item4"
                        },
                        new
                        {
                            Id = new Guid("dd87b7e3-b8eb-4b28-b24b-e53eeb5d5427"),
                            Amount = 214m,
                            Category = 20,
                            CreateDt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Details4",
                            Name = "Item5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
